# -*- coding: utf-8 -*-
"""numpy

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13exy3PdgdOyzBZk_mCuOcOScOj3Me4EQ
"""

my_list = [1,2,3,4,5]
print(my_list)

import numpy as np

array =np.array(my_list, dtype = int)
print(array)

print(type(array))

print(len(array))

print(array.ndim)

print(array.shape)

my_list2 = [1,2,3,4,5]
my_list3 = [2,3,4,5,6]
my_list4 = [9,7,6,5,4]

mul_arr  = np.array([my_list2,my_list3,my_list4])
print(mul_arr) 

print(mul_arr.shape)

mul_arr.reshape(1,15)

a = np.array([[1,2,3],[4,5,6]])
print(a.shape)

a.shape = (3,2)
print(a)

r = range(24)
print(r)

a = np.arange(24)
print(a)
print(a.ndim)

b = a.reshape(6,4,1)
print(b)

x= np.array([1,2,3,4,5] , dtype=np.int8)
print(x.itemsize)

x= np.array([1,2,3,4,5] , dtype = np.float32)
print(x.itemsize)

x = np.array([[1,2],[3,4]] , dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)
print(x)
print(y)

print(x+y)
print(np.add(x,y))

print(x-y)
print(np.subtract(x,y))

print(x*y)
print(np.multiply(x,y))
print(x.dot(y))

'''[[37  40] 
 [85  92]] 
 dot product =[[1*11+2*13, 1*12+2*14],[3*11+4*13, 3*12+4*14]]
'''

print(x.dot(y))
print(np.dot(x,y))

print(x/y)
print(np.divide(x,y))

print(np.sum(x)) #sum of all elements
print(np.sum(x,axis=0)) #sum of each column
print(np.sum(y,axis=0)) #sum of each row